### ISSUE TITLE
wifi_extender.ino:123:5: error: 'dhcpSoftAP' was not declared in this scope

### ISSUE THREAD

**Issue by alarik84** [Pius171/esp8266-wifi-extender#5]
Hi.
Following exception is thrown during compilation process. If it's declared as an instance of DhcpServer, dns excpetions are thrown further.

ifi_extender.ino:123:5: error: 'dhcpSoftAP' was not declared in this scope
  123 |     dhcpSoftAP.dhcps_set_dns(0, WiFi.dnsIP(0));

WM.cpp:136:7: error: control reaches end of non-void function [-Werror=return-type]
  136 |       });

**Comment by rucko24** [comment]
> Hi. Following exception is thrown during compilation process. If it's declared as an instance of DhcpServer, dns excpetions are thrown further.
> 
> ifi_extender.ino:123:5: error: 'dhcpSoftAP' was not declared in this scope 123 | dhcpSoftAP.dhcps_set_dns(0, WiFi.dnsIP(0));
> 
> WM.cpp:136:7: error: control reaches end of non-void function [-Werror=return-type] 136 | });

chage with 

```c++
auto& server1 = WiFi.softAPDhcpServer();
server1.setDns(WiFi.dnsIP(0));
```

The strange thing is that it only works for me is the firmware once flashed, when flashing the .ino code itself I don't have internet access. 

And it's time to take something into account. 

- The SSID must not have spaces
- The ssid password I have is no longer than 10 characters, because otherwise, I would not connect.

**Comment by rucko24** [comment]
This works for me...

```c++
auto& server1 = WiFi.softAPDhcpServer();
server1.setDns(WiFi.dnsIP(0)); <1>
server1.setDns(WiFi.dnsIP(1)); <2>
```
<1> First DNS, like maybe 192.168.1.1
<2> Second DNS, from your ISP provider.

these ip addresses will be automatically obtained from your network.

**Comment by TomiSzabo00** [comment]
> This works for me...
> 
> ```c++
> auto& server1 = WiFi.softAPDhcpServer();
> server1.setDns(WiFi.dnsIP(0)); <1>
> server1.setDns(WiFi.dnsIP(1)); <2>
> ```
> 
> <1> First DNS, like maybe 192.168.1.1 <2> Second DNS, from your ISP provider.

Hi, this indeed fixed the first issue mentioned by @alarik84. `dhcpSoftAp` is not a problem anymore but i still get
`src/WM.cpp:136:7: error: control reaches end of non-void function [-Werror=return-type]`
when trying to build it. Could @rucko24 or @Pius171 take a further look into this? It would me much appreciated :)

**Comment by rucko24** [comment]
> > This works for me...
> > ```c++
> > auto& server1 = WiFi.softAPDhcpServer();
> > server1.setDns(WiFi.dnsIP(0)); <1>
> > server1.setDns(WiFi.dnsIP(1)); <2>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <1> First DNS, like maybe 192.168.1.1 <2> Second DNS, from your ISP provider.
> 
> Hi, this indeed fixed the first issue mentioned by @alarik84. `dhcpSoftAp` is not a problem anymore but i still get `src/WM.cpp:136:7: error: control reaches end of non-void function [-Werror=return-type]` when trying to build it. Could @rucko24 or @Pius171 take a further look into this? It would me much appreciated :)

Which version of the esp8266 SDK are you using? 

```c++
auto& server1 = WiFi.softAPDhcpServer();
server1.setDns(WiFi.dnsIP(0));
server1.setDns(WiFi.dnsIP(1));
```
This work with 3.1.1 SDK of ESP8266 partner

---

- Try with https://github.com/esp8266/Arduino/tree/2.7.4
- or https://github.com/esp8266/Arduino/tree/3.0.0

You must install it on your pc, with the arduino IDE you can help you, that is, if you need a version of these, you must uninstall one of them (so I did).

**Comment by TomiSzabo00** [comment]
Okay, so after after about 45 minutes of trial and error I managed to make it work.

Originally, I was using the currently `latest` version (`3.1.2`) of the ESP8266 SDK. With this version, and every version above `3.0.0` would give the originally mentioned error of
```
ifi_extender.ino:123:5: error: 'dhcpSoftAP' was not declared in this scope
```
And if I changed the code to your solution, it seemed like it was fixed, but got the
```
WM.cpp:136:7: error: control reaches end of non-void function [-Werror=return-type]
```
error instead.

Since you mentioned trying the 3.0.0 version of the SDK, i installed it, but now the new, fixed code would have errors, saying something like
```
WiFi has no method called softAPDhcpServer
```
or something similar.

But when I reverted the code the original, and still using the `3.0.0` version SDK it finally built.

So if anyone stumbles upon this problem, above is the solution. Thanks @rucko24 for helping out!. I guess this issue can be closed.

**Comment by rucko24** [comment]
> Okay, so after after about 45 minutes of trial and error I managed to make it work.
> 
> Originally, I was using the currently `latest` version (`3.1.2`) of the ESP8266 SDK. With this version, and every version above `3.0.0` would give the originally mentioned error of
> 
> ```
> ifi_extender.ino:123:5: error: 'dhcpSoftAP' was not declared in this scope
> ```
> 
> And if I changed the code to your solution, it seemed like it was fixed, but got the
> 
> ```
> WM.cpp:136:7: error: control reaches end of non-void function [-Werror=return-type]
> ```
> 
> error instead.
> 
> Since you mentioned trying the 3.0.0 version of the SDK, i installed it, but now the new, fixed code would have errors, saying something like
> 
> ```
> WiFi has no method called softAPDhcpServer
> ```
> 
> or something similar.
> 
> But when I reverted the code the original, and still using the `3.0.0` version SDK it finally built.
> 
> So if anyone stumbles upon this problem, above is the solution. Thanks @rucko24 for helping out!. I guess this issue can be closed.

excellent move partner. 

but one thing, try to try, I have noticed that the nodemcu mine, sometimes loses connection, I do not know if it is because of the lack of hardware or design of it when it comes to function as a repeater.

**Comment by sourabh53525** [comment]
@TomiSzabo00  Can you please let me know how you identified the version of SDK you are using 
How to uninstall it and install the 3.0.0 version of SDK

**Comment by TomiSzabo00** [comment]
Sure @sourabh53525 ! Using the Arduino IDE, open the `Boards Manager`. Simply type in the search field `esp8266` and you will only get one result. 

 - For the current version look on the top left side, just under the library's name.
  - To change the versions you can do the following: 
    1. On the bottom left side you can see the version number.
    2. Click on it, and select the version you would like to install.
    3. Click on install.

Here is a screenshot, hope this helps :)

![image](https://user-images.githubusercontent.com/79201832/230363263-16443903-7431-4d30-bdf8-60777c2196f6.png)

**Comment by sourabh53525** [comment]
oh ok ok

**Comment by ahmedosama07** [comment]
> Okay, so after after about 45 minutes of trial and error I managed to make it work.
> 
> Originally, I was using the currently `latest` version (`3.1.2`) of the ESP8266 SDK. With this version, and every version above `3.0.0` would give the originally mentioned error of
> 
> ```
> ifi_extender.ino:123:5: error: 'dhcpSoftAP' was not declared in this scope
> ```
> 
> And if I changed the code to your solution, it seemed like it was fixed, but got the
> 
> ```
> WM.cpp:136:7: error: control reaches end of non-void function [-Werror=return-type]
> ```
> 
> error instead.
> 
> Since you mentioned trying the 3.0.0 version of the SDK, i installed it, but now the new, fixed code would have errors, saying something like
> 
> ```
> WiFi has no method called softAPDhcpServer
> ```
> 
> or something similar.
> 
> But when I reverted the code the original, and still using the `3.0.0` version SDK it finally built.
> 
> So if anyone stumbles upon this problem, above is the solution. Thanks @rucko24 for helping out!. I guess this issue can be closed.

I tried this solution but it gives me `error compiling for board nodemcu 0.9 (esp-12 module)` so if you can help it would be much appreciated
Also if @rucko24 or @Pius171 can help it would be great.

**Comment by ahmedosama07** [comment]
> > Okay, so after after about 45 minutes of trial and error I managed to make it work.
> > Originally, I was using the currently `latest` version (`3.1.2`) of the ESP8266 SDK. With this version, and every version above `3.0.0` would give the originally mentioned error of
> > ```
> > ifi_extender.ino:123:5: error: 'dhcpSoftAP' was not declared in this scope
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And if I changed the code to your solution, it seemed like it was fixed, but got the
> > ```
> > WM.cpp:136:7: error: control reaches end of non-void function [-Werror=return-type]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > error instead.
> > Since you mentioned trying the 3.0.0 version of the SDK, i installed it, but now the new, fixed code would have errors, saying something like
> > ```
> > WiFi has no method called softAPDhcpServer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or something similar.
> > But when I reverted the code the original, and still using the `3.0.0` version SDK it finally built.
> > So if anyone stumbles upon this problem, above is the solution. Thanks @rucko24 for helping out!. I guess this issue can be closed.
> 
> I tried this solution but it gives me `error compiling for board nodemcu 0.9 (esp-12 module)` so if you can help it would be much appreciated Also if @rucko24 or @Pius171 can help it would be great.

I managed to fix it by using the original code with the edit mentioned [here](https://github.com/Pius171/esp8266-wifi-extender/issues/5#issuecomment-1464943894) and adding a `return` where the error is highlighted in the IDE (I don't know if it's a right thing) but the error says `WM.cpp:136:7: error: control reaches end of non-void function [-Werror=return-type]` which means it needs a `return`

**Comment by alarik84** [comment]
I think this can be closed. For me it also work solution mentioned by @rucko24, adapted in my project as:

`auto& server = WiFi.softAPDhcpServer();
  server.setDns(WiFi.dnsIP(0));
  
  WiFi.softAPConfig( // Set IP Address, Gateway and Subnet
    IPAddress(192, 168, 100, 1),
    IPAddress(192, 168, 100, 1),
    IPAddress(255, 255, 255, 0));
  WiFi.softAP(SOFTAP_WIFI_SSID, SOFTAP_WIFI_PASS, CHANNEL);`

Thank you all for all your contribution.
